repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
        -   id: black
-   repo: https://github.com/life4/flakehell
    rev: v.0.7.1
    hooks:
        -   id: flakehell
            name: flakehell
            language: system
            types: ["file", "text"]
            files: \.(ipynb|md|py|rst|yaml|yml)$
            entry: poetry run flakehell lint
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
        -   id: isort
            files: "\\.(py)$"
            args: [--settings-path=pyproject.toml]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.19.0
    hooks:
        -   id: commitizen
            stages: [commit-msg]
